name= input("Please tell me yout name! \n\t")
print("Hi " + name)
name=input("Give me another name \n\t")
print(name + " is a pretty cool name!")
print("I wish my name was " + name)

name=input("Tell me your name now ")
email=input("Let me send you spam ")
nickname=input("What do your friends call you? ")
print("Hey "+name+" or should i say "+nickname+".")
print("I am going to send you a bunch of spam at "+email+".")